void die(char *s);
void add_vt(struct Process *proc,struct var_table *vt);
void add_proc(struct Process *proc);
void add_node(struct instruction_node *node,struct Process *proc);
void add_thread(struct process_thread *thread,struct process_task *task);
void add_task(struct process_task *task);
void del_task(struct process_task *task);
void addr2coords(int addr,int *x,int *y);
void get_p_attr(int ID,char *car,int *col);
void add_killed_task(struct process_task *task);
void add_thread_rev(struct process_thread *thread,struct process_task *task);
